#pragma once

#define TELEMETRY_PROP_NAME_COM_STATE "comState"
#define TELEMETRY_PROP_NAME_TIMESTAMP "timestamp"
#define TELEMETRY_PROP_NAME_VOLTAGE_L1N "voltageL1N"
#define TELEMETRY_PROP_NAME_VOLTAGE_L2N "voltageL2N"
#define TELEMETRY_PROP_NAME_VOLTAGE_L3N "voltageL3N"
#define TELEMETRY_PROP_NAME_AVG_VOLTAGE_LN "avgVoltageLN"
#define TELEMETRY_PROP_NAME_VOLTAGE_L1L2 "voltageL1L2"
#define TELEMETRY_PROP_NAME_VOLTAGE_L2L3 "voltageL2L3"
#define TELEMETRY_PROP_NAME_VOLTAGE_L1L3 "voltageL1L3"
#define TELEMETRY_PROP_NAME_AVG_VOLTAGE_LL "avgVoltageLL"
#define TELEMETRY_PROP_NAME_CURRENT_L1 "currentL1"
#define TELEMETRY_PROP_NAME_CURRENT_L2 "currentL2"
#define TELEMETRY_PROP_NAME_CURRENT_L3 "currentL3"
#define TELEMETRY_PROP_NAME_CURRENT_NEUTRAL "currentNeutral"
#define TELEMETRY_PROP_NAME_AVG_CURRENTL "avgCurrentL"
#define TELEMETRY_PROP_NAME_CURRENT_TOTAL "currentTotal"
#define TELEMETRY_PROP_NAME_REAL_POWER_L1N "realPowerL1N"
#define TELEMETRY_PROP_NAME_REAL_POWER_L2N "realPowerL2N"
#define TELEMETRY_PROP_NAME_REAL_POWER_L3N "realPowerL3N"
#define TELEMETRY_PROP_NAME_REAL_POWER_TOTAL "realPowerTotal"
#define TELEMETRY_PROP_NAME_APPARENT_POWER_L1N "apparentPowerL1N"
#define TELEMETRY_PROP_NAME_APPARENT_POWER_L2N "apparentPowerL2N"
#define TELEMETRY_PROP_NAME_APPARENT_POWER_L3N "apparentPowerL3N"
#define TELEMETRY_PROP_NAME_APPARENT_POWER_TOTAL "apparentPowerTotal"
#define TELEMETRY_PROP_NAME_REACTIVE_POWER_L1N "reactivePowerL1N"
#define TELEMETRY_PROP_NAME_REACTIVE_POWER_L2N "reactivePowerL2N"
#define TELEMETRY_PROP_NAME_REACTIVE_POWER_L3N "reactivePowerL3N"
#define TELEMETRY_PROP_NAME_REACTIVE_POWER_TOTAL "reactivePowerTotal"
#define TELEMETRY_PROP_NAME_COS_PHI_L1 "cosPhiL1"
#define TELEMETRY_PROP_NAME_COS_PHI_L2 "cosPhiL2"
#define TELEMETRY_PROP_NAME_COS_PHI_L3 "cosPhiL3"
#define TELEMETRY_PROP_NAME_AVG_COS_PHI "avgCosPhi"
#define TELEMETRY_PROP_NAME_FREQUENCY "frequency"
#define TELEMETRY_PROP_NAME_ROT_FIELD "rotField"
#define TELEMETRY_PROP_NAME_REAL_ENERGY_L1N "realEnergyL1N"
#define TELEMETRY_PROP_NAME_REAL_ENERGY_L2N "realEnergyL2N"
#define TELEMETRY_PROP_NAME_REAL_ENERGY_L3N "realEnergyL3N"
#define TELEMETRY_PROP_NAME_REAL_ENERGY_TOTAL "realEnergyTotal"
#define TELEMETRY_PROP_NAME_APPARENT_ENERGY_L1 "apparentEnergyL1"
#define TELEMETRY_PROP_NAME_APPARENT_ENERGY_L2 "apparentEnergyL2"
#define TELEMETRY_PROP_NAME_APPARENT_ENERGY_L3 "apparentEnergyL3"
#define TELEMETRY_PROP_NAME_APPARENT_ENERGY_TOTAL "apparentEnergyTotal"
#define TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L1 "reactiveEnergyL1"
#define TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L2 "reactiveEnergyL2"
#define TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L3 "reactiveEnergyL3"
#define TELEMETRY_PROP_NAME_REACTIVE_ENERGY_TOTAL "reactiveEnergyTotal"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L1N "THDVoltsL1N"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L2N "THDVoltsL2N"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L3N "THDVoltsL3N"
#define TELEMETRY_PROP_NAME_AVG_THD_VOLTS_LN "avgTHDVoltsLN"
#define TELEMETRY_PROP_NAME_THD_CURRENT_L1N "THDCurrentL1N"
#define TELEMETRY_PROP_NAME_THD_CURRENT_L2N "THDCurrentL2N"
#define TELEMETRY_PROP_NAME_THD_CURRENT_L3N "THDCurrentL3N"
#define TELEMETRY_PROP_NAME_AVG_THD_CURRENT_LN "avgTHDCurrentLN"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L1L2 "THDVoltsL1L2"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L2L3 "THDVoltsL2L3"
#define TELEMETRY_PROP_NAME_THD_VOLTS_L1L3 "THDVoltsL1L3"
#define TELEMETRY_PROP_NAME_AVG_THD_VOLTS_LL "avgTHDVoltsLL"
#define TELEMETRY_PROP_NAME_POWER_FACTOR_L1N "powerFactorL1N"
#define TELEMETRY_PROP_NAME_POWER_FACTOR_L2N "powerFactorL2N"
#define TELEMETRY_PROP_NAME_POWER_FACTOR_L3N "powerFactorL3N"
#define TELEMETRY_PROP_NAME_POWER_FACTOR_TOTAL "powerFactorTotal"
#define TELEMETRY_PROP_NAME_COM_STATUS "comState"
#define TELEMETRY_PROP_NAME_TIMESTAMP "timestamp"



enum EM75DataArrayIndex{
 VOLTAGE_L1N_INDEX,
 VOLTAGE_L2N_INDEX,
 VOLTAGE_L3N_INDEX,
 AVG_VOLTAGE_LN_INDEX,
 VOLTAGE_L1L2_INDEX,
 VOLTAGE_L2L3_INDEX,
 VOLTAGE_L1L3_INDEX,
 AVG_VOLTAGE_LL_INDEX,
 CURRENT_L1_INDEX,
 CURRENT_L2_INDEX,
 CURRENT_L3_INDEX,
 CURRENT_NEUTRAL_INDEX,
 AVG_CURRENTL_INDEX,
 CURRENT_TOTAL_INDEX,
 REAL_POWER_L1N_INDEX,
 REAL_POWER_L2N_INDEX,
 REAL_POWER_L3N_INDEX,
 REAL_POWER_TOTAL_INDEX,
 APPARENT_POWER_L1N_INDEX,
 APPARENT_POWER_L2N_INDEX,
 APPARENT_POWER_L3N_INDEX,
 APPARENT_POWER_TOTAL_INDEX,
 REACTIVE_POWER_L1N_INDEX,
 REACTIVE_POWER_L2N_INDEX,
 REACTIVE_POWER_L3N_INDEX,
 REACTIVE_POWER_TOTAL_INDEX,
 COS_PHI_L1_INDEX,
 COS_PHI_L2_INDEX,
 COS_PHI_L3_INDEX,
 AVG_COS_PHI_INDEX,
 FREQUENCY_INDEX,
 ROT_FIELD_INDEX,
 REAL_ENERGY_L1N_INDEX,
 REAL_ENERGY_L2N_INDEX,
 REAL_ENERGY_L3N_INDEX,
 REAL_ENERGY_TOTAL_INDEX,
 APPARENT_ENERGY_L1_INDEX,
 APPARENT_ENERGY_L2_INDEX,
 APPARENT_ENERGY_L3_INDEX,
 APPARENT_ENERGY_TOTAL_INDEX,
 REACTIVE_ENERGY_L1_INDEX,
 REACTIVE_ENERGY_L2_INDEX,
 REACTIVE_ENERGY_L3_INDEX,
 REACTIVE_ENERGY_TOTAL_INDEX,
 THD_VOLTS_L1N_INDEX,
 THD_VOLTS_L2N_INDEX,
 THD_VOLTS_L3N_INDEX,
 AVG_THD_VOLTS_LN_INDEX,
 THD_CURRENT_L1N_INDEX,
 THD_CURRENT_L2N_INDEX,
 THD_CURRENT_L3N_INDEX,
 AVG_THD_CURRENT_LN_INDEX,
 THD_VOLTS_L1L2_INDEX,
 THD_VOLTS_L2L3_INDEX,
 THD_VOLTS_L1L3_INDEX,
 AVG_THD_VOLTS_LL_INDEX,
 POWER_FACTOR_L1N_INDEX,
 POWER_FACTOR_L2N_INDEX,
 POWER_FACTOR_L3N_INDEX,
 POWER_FACTOR_TOTAL_INDEX
};
