#pragma once


extern char* FM_TELEMETRY_PROP_NAME_TOTAL_CONSUMPTION;
extern char* FM_TELEMETRY_PROP_NAME_PERIOD_CONSUMPTION;
extern char* FM_TELEMETRY_PROP_NAME_AVERAGE_FLOW;
extern char* FM_TELEMETRY_PROP_NAME_INITIAL_TIME;
extern char* FM_TELEMETRY_PROP_NAME_FINAL_TIME;
extern char* FM_TELEMETRY_PROP_NAME_ERROR_STATE;
