#pragma once

int isEMDataValid(float data);
double getEMErrorValue(int dataError);
//static const double NO_PREV_DATA_AVAILABLE_ERROR_VALUE = (double)999999999999998;

extern const double NAN_ERROR_VALUE;
extern const double NO_PREV_DATA_AVAILABLE_ERROR_VALUE;
extern const float FLOAT_NO_PREV_DATA_AVAILABLE_ERROR_VALUE;

extern char* EM1PH_DATA_TELEMETRY_NAMES[];
extern char* EM3PH_DATA_TELEMETRY_NAMES[];
extern char* EM1PH_PERIOD_DATA_TELEMETRY_NAMES[];
extern char* EM3PH_PERIOD_DATA_TELEMETRY_NAMES[];

extern char* TELEMETRY_PROP_NAME_COM_STATE;
extern char* TELEMETRY_PROP_NAME_TIMESTAMP;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L1N;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L2N;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L3N;
extern char* TELEMETRY_PROP_NAME_AVG_VOLTAGE_LN;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L1L2;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L2L3;
extern char* TELEMETRY_PROP_NAME_VOLTAGE_L1L3;
extern char* TELEMETRY_PROP_NAME_AVG_VOLTAGE_LL;
extern char* TELEMETRY_PROP_NAME_CURRENT_L1;
extern char* TELEMETRY_PROP_NAME_CURRENT_L2;
extern char* TELEMETRY_PROP_NAME_CURRENT_L3;
extern char* TELEMETRY_PROP_NAME_CURRENT_NEUTRAL;
extern char* TELEMETRY_PROP_NAME_AVG_CURRENTL;
extern char* TELEMETRY_PROP_NAME_CURRENT_TOTAL;
extern char* TELEMETRY_PROP_NAME_REAL_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_REAL_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_REAL_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_REAL_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_APPARENT_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_APPARENT_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_APPARENT_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_APPARENT_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_REACTIVE_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_REACTIVE_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_REACTIVE_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_REACTIVE_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_COS_PHI_L1;
extern char* TELEMETRY_PROP_NAME_COS_PHI_L2;
extern char* TELEMETRY_PROP_NAME_COS_PHI_L3;
extern char* TELEMETRY_PROP_NAME_AVG_COS_PHI;
extern char* TELEMETRY_PROP_NAME_FREQUENCY;
extern char* TELEMETRY_PROP_NAME_ROT_FIELD;
extern char* TELEMETRY_PROP_NAME_REAL_ENERGY_L1N;
extern char* TELEMETRY_PROP_NAME_REAL_ENERGY_L2N;
extern char* TELEMETRY_PROP_NAME_REAL_ENERGY_L3N;
extern char* TELEMETRY_PROP_NAME_REAL_ENERGY_TOTAL;
extern char* TELEMETRY_PROP_NAME_APPARENT_ENERGY_L1;
extern char* TELEMETRY_PROP_NAME_APPARENT_ENERGY_L2;
extern char* TELEMETRY_PROP_NAME_APPARENT_ENERGY_L3;
extern char* TELEMETRY_PROP_NAME_APPARENT_ENERGY_TOTAL;
extern char* TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L1;
extern char* TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L2;
extern char* TELEMETRY_PROP_NAME_REACTIVE_ENERGY_L3;
extern char* TELEMETRY_PROP_NAME_REACTIVE_ENERGY_TOTAL;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L1N;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L2N;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L3N;
extern char* TELEMETRY_PROP_NAME_AVG_THD_VOLTS_LN;
extern char* TELEMETRY_PROP_NAME_THD_CURRENT_L1N;
extern char* TELEMETRY_PROP_NAME_THD_CURRENT_L2N;
extern char* TELEMETRY_PROP_NAME_THD_CURRENT_L3N;
extern char* TELEMETRY_PROP_NAME_AVG_THD_CURRENT_LN;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L1L2;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L2L3;
extern char* TELEMETRY_PROP_NAME_THD_VOLTS_L1L3;
extern char* TELEMETRY_PROP_NAME_AVG_THD_VOLTS_LL;
extern char* TELEMETRY_PROP_NAME_POWER_FACTOR_L1N;
extern char* TELEMETRY_PROP_NAME_POWER_FACTOR_L2N;
extern char* TELEMETRY_PROP_NAME_POWER_FACTOR_L3N;
extern char* TELEMETRY_PROP_NAME_POWER_FACTOR_TOTAL;
extern char* TELEMETRY_PROP_NAME_COM_ERROR;
extern char* TELEMETRY_PROP_NAME_TIMESTAMP;

extern char* TELEMETRY_PROP_NAME_DATA_ERROR_COUNTER;
extern char* TELEMETRY_PROP_NAME_PERIOD_DATA_ERROR_COUNTER;



extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_POWER_L1N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_POWER_L2N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_POWER_L3N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_POWER_TOTAL;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_ENERGY_L1N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_ENERGY_L2N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_ENERGY_L3N;
extern char* TELEMETRY_PROP_NAME_PERIOD_REAL_ENERGY_TOTAL;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_ENERGY_L1;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_ENERGY_L2;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_ENERGY_L3;
extern char* TELEMETRY_PROP_NAME_PERIOD_APPARENT_ENERGY_TOTAL;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_ENERGY_L1;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_ENERGY_L2;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_ENERGY_L3;
extern char* TELEMETRY_PROP_NAME_PERIOD_REACTIVE_ENERGY_TOTAL;


