#pragma once


#define TELEMETRY_PROP_NAME_FREE_HEAP "freeHeap"
#define TELEMETRY_PROP_NAME_HEAP_SIZE "heapSize"
#define TELEMETRY_PROP_NAME_MAX_ALLOC_HEAP "maxAllocHeap"
#define TELEMETRY_PROP_NAME_MIN_FREE_HEAP "minFreeHeap"
#define TELEMETRY_PROP_NAME_SKETCH_SIZE "sketchSize"
#define TELEMETRY_PROP_NAME_INTERNAL_TEMPERATURE "internalTemperature"
#define TELEMETRY_PROP_NAME_RUNNING_TIME "runningTime"
#define TELEMETRY_PROP_NAME_HALL_SENSOR "hallSensor"
#define TELEMETRY_PROP_NAME_TIMESTAMP "timestamp"
