#pragma once


#define WEIDOS_TELEMETRY_PROP_NAME_FREE_HEAP "freeHeap"
#define WEIDOS_TELEMETRY_PROP_NAME_HEAP_SIZE "heapSize"
#define WEIDOS_TELEMETRY_PROP_NAME_MAX_ALLOC_HEAP "maxAllocHeap"
#define WEIDOS_TELEMETRY_PROP_NAME_MIN_FREE_HEAP "minFreeHeap"
#define WEIDOS_TELEMETRY_PROP_NAME_FREE_PSRAM "freePsram"
#define WEIDOS_TELEMETRY_PROP_NAME_PSRAM_SIZE "psramSize"
#define WEIDOS_TELEMETRY_PROP_NAME_MAX_ALLOC_PSRAM "maxAllocPsram"
#define WEIDOS_TELEMETRY_PROP_NAME_MIN_FREE_PSRAM "minFreePsram"
#define WEIDOS_TELEMETRY_PROP_NAME_SKETCH_SIZE "sketchSize"
#define WEIDOS_TELEMETRY_PROP_NAME_INTERNAL_TEMPERATURE "internalTemperature"
#define WEIDOS_TELEMETRY_PROP_NAME_RUNNING_TIME "runningTime"
#define WEIDOS_TELEMETRY_PROP_NAME_HALL_SENSOR "hallSensor"
#define WEIDOS_TELEMETRY_PROP_NAME_TIMESTAMP "timestamp"
#define TELEMETRY_PROP_NAME_BACKUP "backup"
